!grammar spr;
!start <_main_>;

<_main_> :  [<_vocative>] <_questions>  [<_noise>];

<_questions> : <_aq> | <_cq> | <_oq> | <_pq>;

<_aq> : <_aq1> | <_aq2> | <_aq3> | <_aq4> ; 
<_aq1> : <_where> is [located] [<_the>] <_bigobject>;
<_aq2> : in <_which> room is <_the> <_bigobject>;
<_aq3> : <_how> many <_bigobject>  are in the <_room>;
<_aq4> : <_how> many doors has <_the> <_room>;

<_cq> : <_cq1> | <_cq2> | <_cq3> | <_cq4> | <_cq5> | <_cq6> | <_cq7> | <_cq8> | <_cq9> | <_cq10> | <_cq11>;

<_cq1> : <_how> many <_people> are in the crowd ;
<_cq2> : tell me the number of <_people> in <_the> crowd ;

<_people> : people | <_people_phase> | <_people_gender>;
<_people_phase> : children | adults | elders;
<_people_gender> : women | men | males | females | boys | girls ;

<_cq3> : <_how> many people in the crowd are <_gestures_or_postures>;

<_gestures_or_postures> : <_people_gestures> | <_people_postures> | <_or_postures>;
<_people_gestures> : waving | rising left arm | rising right arm | pointintg left | pointing right;
<_people_postures> : standing | sitting | lying ;
<_or_postures> : standing or lying | standing or sitting | sitting or lying;

<_cq4> : was the <_people_postures> person <_or_gender>;
<_cq5> : [tell me if] the <_people_postures> person was a <_person_gender>;

<_person> : <_person_phase> | <_person_gender>;
<_person_gender> : male | female | man | woman | boy | girl;
<_person_phase> : adult | child | elder;
<_or_gender> : male or female | man or woman | boy or girl;

<_cq6> : tell me how many people were wearing <_color>;

<_cq7> : <_how> old do you think i am;
<_cq8> : am i a man or a woman;

<_cq9> : <_what> <_is> <_the> <_number> <_of> <_people_gender> and <_people_gender>;
<_cq10> : <_what> <_is> <_the> <_number> <_of> <_people>;
<_cq11> : <_what> <_is> <_the> size <_of> the crowd ;


<_oq> : <_oq1> | <_oq2> | <_oq3> | <_oq4> | <_oq5> | <_oq6> | <_oq7> | <_oq8> | <_oq9> | <_oq10>| <_oq11> | <_oq12> | <_oq13>;

<_oq1> : <_where> can i find [<_a_the>] <_smallobject> ;
<_oq2> : how many <_category_object> there are;
<_oq3> : <_what> <_is> <_the> colour of <_the> <_smallobject>  ;
<_oq4> : <_how> many <_objects> are in the <_manipulationplace>;
<_oq5> : <_what> objects are [stored] in <_the> <_manipulationplace> ;
<_oq6> : <_where> [can] i find  <_a_the>  <_objects2> ;
<_oq7> : to which category belong <_the> <_smallobject>;
<_oq8> : <_do> <_the> <_smallobject> and <_smallobject> belong to the same category;
<_oq9> : <_which> is the <_object_description> <_objects>;
<_oq10> : between the <_smallobject> and <_smallobject> which one is <_object_comp>;
<_oq11> : [<_a_the>] <_smallobject> and [<_a_the>] <_smallobject> [ do] they belong to <_the> same category ;
<_oq12> : do the objects in <_manipulationplace> belongs to the same category;
<_oq13> : <_where> <_is> <_the> <_object_description> [object];

<_a_the> : a | <_the>;
<_objects> : object | <_category_object>;
<_objects2> : <_smallobject> | <_category_object>;
<_object_description> : smallest | lightest | biggest | heaviest ;
<_object_comp> : heavier | lighter | smaller | bigger;

<_pq> : <_pq1> | <_pq2> | <_pq3> | <_pq4> | <_pq5> | <_pq6> | <_pq7> | <_pq8> | <_pq9> | <_pq10> | <_pq11> | <_pq12> | <_pq13> | <_pq14> | <_pq15> | <_pq16> | <_pq17> | <_pq18> | <_pq19> | <_pq20> | <_pq21> | <_pq22>;
<_pq1> : <_who> invented the C programming language;
<_pq2> : <_when> was invented the C programming language;
<_pq3> : <_when> was invented the B programming language;
<_pq4> : <_where> does the term computer bug come from;
<_pq5> : <_who> invented the first compiler;
<_pq6> : <_which> robot is used in the open platform league;
<_pq7> : <_which> robot is used in the domestic standard platform league;
<_pq8> : <_which> robot is used in the social standard platform league;
<_pq9> : <_how> many people live in the japan;
<_pq10>: <_what> are the colours of the japanese flag;
<_pq11>: <_what> <_is> the capital of japan;
<_pq12>: <_what> is the highest point in japan;
<_pq13>: <_what> is a sakura;
<_pq14>: <_who> is the emperor of japan;
<_pq15>: <_what> <_is> the name of your team;
<_pq16>: <_what> time <_is> it ;
<_pq17>: <_what> day <_is> today;
<_pq18>: do you have dreams;
<_pq19>: in <_which> city will next year's robocup be hosted;
<_pq20>: <_what> <_is> your name ;
<_pq21>: in <_which> year was the robocup founded ;
<_pq22>: <_what> was <_the> last question;


<_room>: kitchen | dinning room | bedroom | living room | office | corridor | bathroom;

<_manipulationplace> : [<_side>] bedside [table] | living shelf | TV stand | living table | center table  | drawer | desk | bar | cupboard | sink | sideshelf | bookcase | dinning table | fridge | counter | cabinet  | couch table | dinner table | kitchen counter | kitchen table | table ;  

<_bigobject>: sofa | bed | shelf | chairs | plant  <_manipulationplace>;

<_category_object> :  snacks | candies | food | drinks | toiletries | containers |objects;

<_smallobject> : <_snacks> | <_candies> | <_food> | <_drinks> | <_toiletries> | <_containers>; 

<_snacks> : chips | senbei | pringles | peanuts;
<_candies> : chocolate [bar] | manju | mints | chocolate [egg] | biscuits | bubblegum | tomatochips | barbecuechips | honeychip | coconutcereals | cocoballs | eggstars ;
<_food> : noodles | apple | paprika | melon | sushi | flakes | oat | gramsoup | beansauce | lemon | pear;
<_drinks> : tea | beer | coke | sake | greentea | papaya milk | pure milk | water | orangejuice | beer;
<_toiletries>: shampoo | soap | cloth | sponge | toiletpaper | lotion | toothpaste;
<_containers>: bowl | mug | glass | tray | plate | box ;

<_color> : red | blue | white | black | green | yellow ;

<_how> : how;
<_what> : what ;
<_where> : where ;
<_when> : when ;
<_which> : which ;
<_who> : who ;
<_do> : do ;
<_is> : is ;
<_the> : the ;
<_are> : are ;
<_number>: number ;
<_of>: of ;
<_side>: left | right;

<_vocative> : robot | pepper | maqui;
<_noise> :  hum | wa | sh | ch | s | mm | pu | tu | ss | huh | naa ;
