!grammar drinks;
!start <_main_>;

<_main_> : [<_response>] <_drinks>;

<_drinks> : coke | sprite | baltica | fanta;

<_vocative> : robot | pepper | maqui;

<_response> : i want [ a ];

<_noise> :  hum | wa | sh | ch | s | mm | pu | tu | ss | huh | naa ;
