!grammar drinks;
!start <_main_>;
 
<_main_> : <_miss_drink_sentence>;

<_miss_drink_sentence> : [<_miss_drink_phrase>]  <_drinks>;
<_miss_drink_phrase> : the missing drink is | there is no ;
<_drinks> : coke | milk | water | tea | beer ;


